[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]
panic-abort-tests = true

[build]
target = "x86_64-rustrial_os.json"

[target.x86_64-rustrial_os]
runner = "bootimage runner --args='-device isa-debug-exit,iobase=0xf4,iosize=0x04'"